import Btn from "../../ui/Btn";

export const recentTransactions = [
  {
    id: 1,
    // head: "Description",
    desc: "Sportify Subscription",
    transactionId: "#125468796",
    type: "Shopping",
    card: "123******",
    date: "28 Jan, 12:30am",
    amount: 25000,
    button: Btn,
    action: "debit",
  },
  {
    id: 2,
    // head: "Transaction ID",
    desc: "Freepik Sales",
    transactionId: "#125468796",
    type: "Transfer",
    card: "123******",
    date: "25 Jan, 10:40pm",
    amount: 750,
    button: Btn,
    action: "credit",
  },
  {
    id: 3,
    // head: "Type",
    desc: "Mobile Service",
    transactionId: "#125468796",
    type: "Service",
    card: "123******",
    date: "20 Jan, 10:40pm",
    amount: 150,
    button: Btn,
    action: "debit",
  },
  {
    id: 4,
    // head: "Type",
    desc: "Wilson",
    transactionId: "#125468796",
    type: "Transfer",
    card: "123******",
    date: "15 Jan, 03:29pm",
    amount: 1050,
    button: Btn,
    action: "debit",
  },
  {
    id: 5,
    // head: "Type",
    desc: "Emily",
    transactionId: "#125468796",
    type: "Transfer",
    card: "123******",
    date: "14 Jan, 10:40pm",
    amount: 840,
    button: Btn,
    action: "credit",
  }
]